spring.application.name=travelbook-backend

# Konfiguracja H2
spring.datasource.url=jdbc:h2:file:./data/travelBookDb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring przeszukuje src/main/resources w poszukiwaniu data.sql
spring.sql.init.mode=always
#hibernate najpeirw sprawdza tworzy tabele a potem odtwarza data.sql
spring.jpa.defer-datasource-initialization=true


# Konsola H2 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect



logging.level.org.springframework.web.cors=DEBUG
logging.level.org.springframework.security=DEBUG


# server.port=8080
# spring.servlet.multipart.max-file-size=10MB
# spring.servlet.multipart.max-request-size=10MB